### ISSUE TITLE
Event to follow the step

### ISSUE THREAD

**Issue by NadsonKT** [ertemishakk/react-formik-stepper#1]
I'm using the plugin, I would like to request an improvement...
I need to monitor the status of the current step, here is an example below

```js
function Component() {
  const [currentStep, setCurrentStep] = useState(1);

  return (
      <FormikStepper 
        onStepChange={setCurrentStep} 
      >
        {/* content */}
      </FormikStepper>
  );
}
```

index.tsx
```js
const FormikStepper = (props: FormikStepperProps) => {
  // ... code ...

  useEffect(() => {
    props.onStepChange(step + 1);
  }, [step]);

  // ... code ...
};
```

**Comment by NadsonKT** [comment]
@ertemishakk

**Comment by ertemishakk** [comment]
@NadsonKT check the example - it already exist. You can access the current step using

`this.props.currentStep`

**Comment by NadsonKT** [comment]
> @NadsonKT check the example - it already exist. You can access the current step using
> 
> `this.props.currentStep`

I understood perfectly, but this props can only be accessed by children, I need to access the "currentStep" outside the "FormikStepper" element

**Comment by NadsonKT** [comment]
@ertemishakk With your permission, I would like to adapt this event as described above. It would help me a lot... and in the future, others might enhance it or even add a hook to it.
